version: "3.5"

services:

  nginx:
    container_name: nginx
    image: "docker.io/bitnami/nginx:latest"
    ports:
    - 8080:8080
    volumes:
    - ./conf/server_block.conf:/opt/bitnami/nginx/conf/server_blocks/server_block.conf:ro
    - ./html:/html
