apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/ollama/
- ../../base/llava-frontend/

patches:
- target: 
    kind: StatefulSet
    name: ollama
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "llava:34b-v1.6"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "16Gi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/nvidia.com~1gpu
      value: 2
- target: 
    kind: Deployment
    name: llava-frontend
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "llava:34b-v1.6"